// <auto-generated />
using System;
using DilekYildizimSensin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DilekYildizimSensin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241205102555_secondMigration2")]
    partial class secondMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DilekYildizimSensin.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("16ea936c-7a28-4c30-86a2-9a9704b6115e"),
                            ConcurrencyStamp = "1767761e-0bda-4c5a-b2a0-284557ebf322",
                            Name = "Superadmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("7cb750cf-3612-4fb4-9f7d-a38ba8f16bf4"),
                            ConcurrencyStamp = "ba7c1f74-1533-4c29-9401-8d41ab5bb7e2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("edf6c246-41d8-475f-8d92-41dddac3aefb"),
                            ConcurrencyStamp = "183406c8-6b6b-4328-8093-f066a48421ff",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb94223b-ccb8-4f2f-93d7-0df96a7f065c"),
                            AccessFailedCount = 0,
                            Age = 25,
                            ConcurrencyStamp = "eda22db8-2940-438c-975c-3fe7b6e69994",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = 2,
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/024/183/525/non_2x/avatar-of-a-man-portrait-of-a-young-guy-illustration-of-male-character-in-modern-color-style-vector.jpg",
                            LastName = "Bey",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIUXiFfe54fHcx5Ikf5L+hCPG/zQ709A/pJ8fMOGOqdazqkxoF/NregHM1vHzlW5Q==",
                            PhoneNumber = "+905439999999",
                            PhoneNumberConfirmed = true,
                            Score = 520,
                            SecurityStamp = "e2a2dd5f-287f-4597-8c59-0d91e9f7970b",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("3aa42229-1c0f-4630-8c1a-db879ecd0427"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "102922dd-28ef-49d9-8d6c-1c29ad8c0b57",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            Gender = 2,
                            ImageUrl = "https://img.freepik.com/premium-photo/graphic-designer-digital-avatar-generative-ai_934475-9292.jpg",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0WuBfJiCVDojlrzUW99/L7j16o9/rzRzzlKIpae7fw/SKQDoxAgWFUZFTUIrxmIg==",
                            PhoneNumber = "+905439999988",
                            PhoneNumberConfirmed = false,
                            Score = 123,
                            SecurityStamp = "f5ef4396-35bd-44b5-80db-b494ac44a585",
                            TwoFactorEnabled = false,
                            UserName = "umutyasar"
                        },
                        new
                        {
                            Id = new Guid("6333d5c1-9fe8-4374-934f-fe0bb6097e04"),
                            AccessFailedCount = 0,
                            Age = 25,
                            ConcurrencyStamp = "729293e7-9a4c-4aac-b638-19bcf1f413a7",
                            Email = "ruken.yavuz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ruken",
                            Gender = 1,
                            ImageUrl = "image1",
                            LastName = "Yavuz",
                            LockoutEnabled = false,
                            NormalizedEmail = "RUKENYAVUZ@GMAIL.COM",
                            NormalizedUserName = "RUKENYAVUZ@GMAIL.COM",
                            PhoneNumber = "+905439999901",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "02bb3422-780d-46a1-8285-357f19404111",
                            TwoFactorEnabled = false,
                            UserName = "Ruken Yavuz"
                        },
                        new
                        {
                            Id = new Guid("935cedfb-b21a-4467-863f-5a94eaebf5de"),
                            AccessFailedCount = 0,
                            Age = 22,
                            ConcurrencyStamp = "1b8b27a7-51da-476c-93e1-ebe875b16a51",
                            Email = "cem.aksu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Cem",
                            Gender = 2,
                            ImageUrl = "image2",
                            LastName = "Aksu",
                            LockoutEnabled = false,
                            NormalizedEmail = "CEMAKSU@GMAIL.COM",
                            NormalizedUserName = "CEMAKSU@GMAIL.COM",
                            PhoneNumber = "+905439999902",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "d7df7d73-1871-4761-a1d6-e558bac212f3",
                            TwoFactorEnabled = false,
                            UserName = "Cem Aksu"
                        },
                        new
                        {
                            Id = new Guid("73f3ff61-bded-4026-b9e3-24b0300646ba"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "beb5e918-be71-44d8-8b34-a05b3a6fbd37",
                            Email = "irem.keles@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "İrem",
                            Gender = 1,
                            ImageUrl = "image3",
                            LastName = "Keleş",
                            LockoutEnabled = false,
                            NormalizedEmail = "IREMKELES@GMAIL.COM",
                            NormalizedUserName = "IREMKELES@GMAIL.COM",
                            PhoneNumber = "+905439999903",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "e7bddd11-198b-4cc7-9950-f9c803ab46b4",
                            TwoFactorEnabled = false,
                            UserName = "İrem Keleş"
                        },
                        new
                        {
                            Id = new Guid("7ce798e5-be51-4e2b-b088-fa8303b0c6ae"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "cc107083-a939-4c21-9dda-1145ee12599f",
                            Email = "hazal.serkaya@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hazal",
                            Gender = 1,
                            ImageUrl = "image4",
                            LastName = "Serkaya",
                            LockoutEnabled = false,
                            NormalizedEmail = "HAZALSERKAYA@GMAIL.COM",
                            NormalizedUserName = "HAZALSERKAYA@GMAIL.COM",
                            PhoneNumber = "+905439999904",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "b8cf5524-fd7d-4b5a-8487-81e39a02d926",
                            TwoFactorEnabled = false,
                            UserName = "Hazal Serkaya"
                        },
                        new
                        {
                            Id = new Guid("76cd1e64-718f-4287-ae00-bdd1394ae9d3"),
                            AccessFailedCount = 0,
                            Age = 23,
                            ConcurrencyStamp = "4b5ac42c-8fe6-4929-8812-8b80392cc20d",
                            Email = "zeynep.sena.celik@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Zeynep Sena",
                            Gender = 1,
                            ImageUrl = "image5",
                            LastName = "Çelik",
                            LockoutEnabled = false,
                            NormalizedEmail = "ZEYNEPSENACELIK@GMAIL.COM",
                            NormalizedUserName = "ZEYNEPSENACELIK@GMAIL.COM",
                            PhoneNumber = "+905439999905",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "227655aa-f100-4283-8912-0abd813b1dab",
                            TwoFactorEnabled = false,
                            UserName = "Zeynep Sena Çelik"
                        },
                        new
                        {
                            Id = new Guid("cde0b89b-f7b3-48ee-bd20-233d2226eddf"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "468d9dc3-1ac4-4237-9996-ac7b6f9f0c49",
                            Email = "ali.ozdemir@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            Gender = 2,
                            ImageUrl = "image6",
                            LastName = "Özdemir",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALIÖZDEMIR@GMAIL.COM",
                            NormalizedUserName = "ALIÖZDEMIR@GMAIL.COM",
                            PhoneNumber = "+905439999906",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "ab227983-9f12-4ccf-9783-182ed4088c30",
                            TwoFactorEnabled = false,
                            UserName = "Ali Özdemir"
                        },
                        new
                        {
                            Id = new Guid("136a133b-6dcd-4c6b-af97-045c7755e25d"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "0c5cb5c3-81dc-4797-b52f-112689f8cf08",
                            Email = "erhan.zorlu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Erhan",
                            Gender = 2,
                            ImageUrl = "image7",
                            LastName = "Zorlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "ERHANZORLU@GMAIL.COM",
                            NormalizedUserName = "ERHANZORLU@GMAIL.COM",
                            PhoneNumber = "+905439999907",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "4acdc2c3-7b04-4989-a7ab-9bcd11d1f5e5",
                            TwoFactorEnabled = false,
                            UserName = "Erhan Zorlu"
                        },
                        new
                        {
                            Id = new Guid("0452596d-90f6-4d24-8efc-6b4a81499102"),
                            AccessFailedCount = 0,
                            Age = 21,
                            ConcurrencyStamp = "a967761f-c57c-4f63-aa51-d14da2a36097",
                            Email = "yagmur.ay@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Yağmur",
                            Gender = 1,
                            ImageUrl = "image8",
                            LastName = "Ay",
                            LockoutEnabled = false,
                            NormalizedEmail = "YAĞMURAY@GMAIL.COM",
                            NormalizedUserName = "YAĞMURAY@GMAIL.COM",
                            PhoneNumber = "+905439999908",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "b26adf30-a95c-4ca4-80ce-cdbdbc72aa8a",
                            TwoFactorEnabled = false,
                            UserName = "Yağmur Ay"
                        },
                        new
                        {
                            Id = new Guid("ac22e14f-a8b7-4a74-ba73-657562db8718"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "a8c4c31e-950e-4d42-87c0-c4645773673e",
                            Email = "nora.ipekci@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nora",
                            Gender = 1,
                            ImageUrl = "image9",
                            LastName = "İpekçi",
                            LockoutEnabled = false,
                            NormalizedEmail = "NORAİPEKÇİ@GMAIL.COM",
                            NormalizedUserName = "NORAİPEKÇİ@GMAIL.COM",
                            PhoneNumber = "+905439999909",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "205259c6-031c-4ec1-a99f-fa4a02cafefd",
                            TwoFactorEnabled = false,
                            UserName = "Nora İpekçi"
                        },
                        new
                        {
                            Id = new Guid("418bcd35-fd7f-4216-8ef3-347b0ea921d4"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "4fe43f1e-21d9-4034-8e7a-93f8b02bf7f8",
                            Email = "melike.ozdil@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Melike",
                            Gender = 1,
                            ImageUrl = "image10",
                            LastName = "Özdil",
                            LockoutEnabled = false,
                            NormalizedEmail = "MELIKEÖZDIL@GMAIL.COM",
                            NormalizedUserName = "MELIKEÖZDIL@GMAIL.COM",
                            PhoneNumber = "+905439999910",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "de4d0284-c6d6-40af-b21a-ea4271b4cc38",
                            TwoFactorEnabled = false,
                            UserName = "Melike Özdil"
                        },
                        new
                        {
                            Id = new Guid("ab1518ac-f42e-4e76-9d09-de2a8e8197fc"),
                            AccessFailedCount = 0,
                            Age = 29,
                            ConcurrencyStamp = "4627b2b0-93e5-4227-bef0-e589564c6fd5",
                            Email = "alper.goksel.yilmaz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Alper Göksel",
                            Gender = 2,
                            ImageUrl = "image11",
                            LastName = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALPERGOKSELYILMAZ@GMAIL.COM",
                            NormalizedUserName = "ALPERGOKSELYILMAZ@GMAIL.COM",
                            PhoneNumber = "+905439999911",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "7628f070-0879-4687-98c1-5e11e618c27f",
                            TwoFactorEnabled = false,
                            UserName = "Alper Göksel Yılmaz"
                        },
                        new
                        {
                            Id = new Guid("fe9dfd01-c7dd-4eb4-918c-a248eb745e8d"),
                            AccessFailedCount = 0,
                            Age = 23,
                            ConcurrencyStamp = "4cf5aeaa-856f-4a97-ba2a-77dda170402a",
                            Email = "saliha.canigur@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Saliha",
                            Gender = 1,
                            ImageUrl = "image12",
                            LastName = "Canıgür",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALIHACANIGUR@GMAIL.COM",
                            NormalizedUserName = "SALIHACANIGUR@GMAIL.COM",
                            PhoneNumber = "+905439999912",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "607fe35f-4792-47ee-82f8-5042a9aab155",
                            TwoFactorEnabled = false,
                            UserName = "Saliha Canıgür"
                        },
                        new
                        {
                            Id = new Guid("4e17ba14-0989-40e8-a6bc-c91a0fb45db7"),
                            AccessFailedCount = 0,
                            Age = 31,
                            ConcurrencyStamp = "d2559bbc-a7dd-4545-95b5-d9b401d20c63",
                            Email = "huseyin.adas@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hüseyin",
                            Gender = 2,
                            ImageUrl = "image13",
                            LastName = "Adaş",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUSEYINADAS@GMAIL.COM",
                            NormalizedUserName = "HUSEYINADAS@GMAIL.COM",
                            PhoneNumber = "+905439999913",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "8bd6c7f5-48eb-4280-9af5-8b146be33337",
                            TwoFactorEnabled = false,
                            UserName = "Hüseyin Adaş"
                        },
                        new
                        {
                            Id = new Guid("467c7977-4976-4505-9c59-def9da0d5df2"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "13c90feb-4952-4120-a846-716898a340dd",
                            Email = "ferit.erden@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ferit",
                            Gender = 2,
                            ImageUrl = "image14",
                            LastName = "Erden",
                            LockoutEnabled = false,
                            NormalizedEmail = "FERITERDEN@GMAIL.COM",
                            NormalizedUserName = "FERITERDEN@GMAIL.COM",
                            PhoneNumber = "+905439999914",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "a2e107c6-1a1a-4289-b047-2707ae80bd3e",
                            TwoFactorEnabled = false,
                            UserName = "Ferit Erden"
                        },
                        new
                        {
                            Id = new Guid("a65f8911-b7f7-48c3-bea0-767e8d973062"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "ad22fdd6-9edc-4cf3-aa03-0d5795d32171",
                            Email = "nergis@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nergis",
                            Gender = 1,
                            ImageUrl = "image15",
                            LastName = "Gül",
                            LockoutEnabled = false,
                            NormalizedEmail = "NERGIS@GMAIL.COM",
                            NormalizedUserName = "NERGIS@GMAIL.COM",
                            PhoneNumber = "+905439999915",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "7f6fb6fa-27e6-4171-9071-c7ab3e9d1905",
                            TwoFactorEnabled = false,
                            UserName = "Nergis Gül"
                        },
                        new
                        {
                            Id = new Guid("c61ab456-b44d-44f5-946a-34035cfe61c5"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "43d654ff-179a-4aed-9730-bdc1618ffd11",
                            Email = "ilayda.celebi@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "İlayda",
                            Gender = 1,
                            ImageUrl = "image16",
                            LastName = "Çelebi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ILAYDACELEBI@GMAIL.COM",
                            NormalizedUserName = "ILAYDACELEBI@GMAIL.COM",
                            PhoneNumber = "+905439999916",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "3ed7d244-5aba-41e8-b4d0-da55a1c63ae7",
                            TwoFactorEnabled = false,
                            UserName = "İlayda Çelebi"
                        },
                        new
                        {
                            Id = new Guid("9c603629-3e7a-4754-852e-5de4163b4539"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "706adf38-4e5a-40dd-94dc-245c953fa016",
                            Email = "gokhan.sahin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Gökhan",
                            Gender = 2,
                            ImageUrl = "image17",
                            LastName = "Şahin",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOKHANSHAHIN@GMAIL.COM",
                            NormalizedUserName = "GOKHANSHAHIN@GMAIL.COM",
                            PhoneNumber = "+905439999917",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "d4407f5c-3e05-415d-a24d-59e5aa53d782",
                            TwoFactorEnabled = false,
                            UserName = "Gökhan Şahin"
                        },
                        new
                        {
                            Id = new Guid("124ece03-ece3-4a21-a276-ab5333b2c820"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "3ff32813-f7ff-48a5-8ef8-0537d4309038",
                            Email = "ozge.akar@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Özge",
                            Gender = 1,
                            ImageUrl = "image18",
                            LastName = "Akar",
                            LockoutEnabled = false,
                            NormalizedEmail = "OZGEAKAR@GMAIL.COM",
                            NormalizedUserName = "OZGEAKAR@GMAIL.COM",
                            PhoneNumber = "+905439999918",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "5525ac24-244c-460f-b184-c0dc5c28ff38",
                            TwoFactorEnabled = false,
                            UserName = "Özge Akar"
                        },
                        new
                        {
                            Id = new Guid("7966ffe5-fb14-4361-b6d8-e26bf91054f1"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "0d4d3dc6-1ae0-4ff7-92cc-d59a18ed6404",
                            Email = "ipek.gurdamar@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "İpek",
                            Gender = 1,
                            ImageUrl = "image19",
                            LastName = "Gürdamar",
                            LockoutEnabled = false,
                            NormalizedEmail = "IPEKGURDAMAR@GMAIL.COM",
                            NormalizedUserName = "IPEKGURDAMAR@GMAIL.COM",
                            PhoneNumber = "+905439999919",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "4d77c57b-606b-41be-8246-950926d048ac",
                            TwoFactorEnabled = false,
                            UserName = "İpek Gürdamar"
                        },
                        new
                        {
                            Id = new Guid("d6ce6b9f-0c88-405b-95e6-f823d87b80ee"),
                            AccessFailedCount = 0,
                            Age = 22,
                            ConcurrencyStamp = "876f8c77-00ee-4eb3-ac89-bb4a0a6de0bb",
                            Email = "melisa.ertan@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Melisa",
                            Gender = 1,
                            ImageUrl = "image20",
                            LastName = "Ertan",
                            LockoutEnabled = false,
                            NormalizedEmail = "MELISAERTAN@GMAIL.COM",
                            NormalizedUserName = "MELISAERTAN@GMAIL.COM",
                            PhoneNumber = "+905439999920",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "d7d6b83a-d7a1-48ce-b59d-72ad0415e9c8",
                            TwoFactorEnabled = false,
                            UserName = "Melisa Ertan"
                        },
                        new
                        {
                            Id = new Guid("7c06f2c7-8b48-409c-b59c-5eb63d98d065"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "b0bd119e-2c1e-4ab1-a199-ab5ab9966d55",
                            Email = "armagan.yagci@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Armağan",
                            Gender = 2,
                            ImageUrl = "image21",
                            LastName = "Yağcı",
                            LockoutEnabled = false,
                            NormalizedEmail = "ARMAGANYAGCI@GMAIL.COM",
                            NormalizedUserName = "ARMAGANYAGCI@GMAIL.COM",
                            PhoneNumber = "+905439999921",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "c94567c6-ba86-4c62-8d98-0a2215ea311f",
                            TwoFactorEnabled = false,
                            UserName = "Armağan Yağcı"
                        },
                        new
                        {
                            Id = new Guid("ed239b07-84f4-4112-97c5-bcc7b54592ac"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "7bc39773-d183-4fe5-8e18-f657de7df32b",
                            Email = "filiz.cetin.narsap@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Filiz",
                            Gender = 1,
                            ImageUrl = "image22",
                            LastName = "Çetin Narşap",
                            LockoutEnabled = false,
                            NormalizedEmail = "FILIZCETINNARSAP@GMAIL.COM",
                            NormalizedUserName = "FILIZCETINNARSAP@GMAIL.COM",
                            PhoneNumber = "+905439999922",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "67a31a4c-9beb-4aec-9b17-efaf2c25ad6d",
                            TwoFactorEnabled = false,
                            UserName = "Filiz Çetin Narşap"
                        },
                        new
                        {
                            Id = new Guid("dfc61d6c-28e0-41e8-990a-71efcbabfc76"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "c2652cff-fcb9-4de2-b5e2-c71e7fa63858",
                            Email = "hande.eren@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hande",
                            Gender = 1,
                            ImageUrl = "image23",
                            LastName = "Eren",
                            LockoutEnabled = false,
                            NormalizedEmail = "HANDEREN@GMAIL.COM",
                            NormalizedUserName = "HANDEREN@GMAIL.COM",
                            PhoneNumber = "+905439999923",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "b83befd8-f76e-456c-b9f8-1ad894e583bf",
                            TwoFactorEnabled = false,
                            UserName = "Hande Eren"
                        },
                        new
                        {
                            Id = new Guid("55e1f309-4b77-4d04-83ea-79dd2c8de826"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "96b99d33-5123-4bec-b6b2-cbed54099200",
                            Email = "nergis.aktas@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nergis",
                            Gender = 1,
                            ImageUrl = "image24",
                            LastName = "Aktaş",
                            LockoutEnabled = false,
                            NormalizedEmail = "NERGISAKTAS@GMAIL.COM",
                            NormalizedUserName = "NERGISAKTAS@GMAIL.COM",
                            PhoneNumber = "+905439999924",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "507b071f-be7b-40d4-9ac1-c6fbd064abe4",
                            TwoFactorEnabled = false,
                            UserName = "Nergis Aktaş"
                        },
                        new
                        {
                            Id = new Guid("2d7c8a37-2c51-45cb-9018-5a17272b9bb9"),
                            AccessFailedCount = 0,
                            Age = 29,
                            ConcurrencyStamp = "cc2889b4-98ef-4a7d-a6df-9a1a8171f824",
                            Email = "gunsu.berber@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Günsu",
                            Gender = 1,
                            ImageUrl = "image25",
                            LastName = "Berber",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUNSUBERBER@GMAIL.COM",
                            NormalizedUserName = "GUNSUBERBER@GMAIL.COM",
                            PhoneNumber = "+905439999925",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "d0d2e54e-983e-4632-9035-07d04320517c",
                            TwoFactorEnabled = false,
                            UserName = "Günsu Berber"
                        },
                        new
                        {
                            Id = new Guid("89e0e7a3-db1e-45d8-a5b7-806472a0db1a"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "c7045517-7dea-4f4f-9903-8a79291c3e67",
                            Email = "melike.ozdil@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Melike",
                            Gender = 1,
                            ImageUrl = "image26",
                            LastName = "Özdil",
                            LockoutEnabled = false,
                            NormalizedEmail = "MELIKEOZDIL@GMAIL.COM",
                            NormalizedUserName = "MELIKEOZDIL@GMAIL.COM",
                            PhoneNumber = "+905439999926",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "0af004c1-01b1-4952-a1eb-ad25ad534b95",
                            TwoFactorEnabled = false,
                            UserName = "Melike Özdil"
                        },
                        new
                        {
                            Id = new Guid("6dd61d40-425f-46d9-8282-2d1b2aea8c05"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "e1b35f8c-6249-48d9-bf05-ebd73a4bff91",
                            Email = "yasemin.kocaman@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yasemin",
                            Gender = 1,
                            ImageUrl = "image27",
                            LastName = "Kocaman",
                            LockoutEnabled = false,
                            NormalizedEmail = "YASEMINKOCAMAN@GMAIL.COM",
                            NormalizedUserName = "YASEMINKOCAMAN@GMAIL.COM",
                            PhoneNumber = "+905439999927",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "655da1dd-bf7d-4b95-a673-c15bf7fe8373",
                            TwoFactorEnabled = false,
                            UserName = "Yasemin Kocaman"
                        },
                        new
                        {
                            Id = new Guid("ce69eaed-61b7-40b1-9902-998e1363376e"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "9d28cf4a-2053-4e9c-8a80-4c5674c647cd",
                            Email = "aysenur.cetin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ayşe Nur",
                            Gender = 1,
                            ImageUrl = "image27",
                            LastName = "Çetin",
                            LockoutEnabled = false,
                            NormalizedEmail = "AYSENURCETIN@GMAIL.COM",
                            NormalizedUserName = "AYSENURCETIN@GMAIL.COM",
                            PhoneNumber = "+905439999927",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "cf4a0484-cad1-4345-9af2-d0f6262ebfa0",
                            TwoFactorEnabled = false,
                            UserName = "Ayşe Nur Çetin"
                        },
                        new
                        {
                            Id = new Guid("73e19ecd-7069-4c03-ae90-e349a496c312"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "cc00637e-403a-40d5-9631-065561485f2a",
                            Email = "seyda.muftuoglu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Şeyda",
                            Gender = 1,
                            ImageUrl = "image29",
                            LastName = "Müftüoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "SEYDAMUFTUOGLU@GMAIL.COM",
                            NormalizedUserName = "SEYDAMUFTUOGLU@GMAIL.COM",
                            PhoneNumber = "+905439999929",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "89d4abe8-0894-441c-8077-81aeb71c236a",
                            TwoFactorEnabled = false,
                            UserName = "Şeyda Müftüoğlu"
                        },
                        new
                        {
                            Id = new Guid("f7825909-442c-4bd7-9b30-211406fc7961"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "ba501e99-01cd-4ba0-896f-12b365a48256",
                            Email = "goksu.gokcesu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Göksu",
                            Gender = 1,
                            ImageUrl = "image30",
                            LastName = "Gökçesu",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOKSUGOKCESU@GMAIL.COM",
                            NormalizedUserName = "GOKSUGOKCESU@GMAIL.COM",
                            PhoneNumber = "+905439999930",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "d16614c1-42d1-45f2-b693-6f446b5d809e",
                            TwoFactorEnabled = false,
                            UserName = "Göksu Gökçesu"
                        },
                        new
                        {
                            Id = new Guid("a27d62ac-c8f3-4481-b501-b53bafc189b6"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "ddebb9da-426a-4bee-a863-5a61a3e53ec3",
                            Email = "sevval.vural@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Şevval",
                            Gender = 1,
                            ImageUrl = "image31",
                            LastName = "Vural",
                            LockoutEnabled = false,
                            NormalizedEmail = "SEVVALVURAL@GMAIL.COM",
                            NormalizedUserName = "SEVVALVURAL@GMAIL.COM",
                            PhoneNumber = "+905439999931",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "3baf7da2-c16d-415d-b30a-244ce5c1b3fe",
                            TwoFactorEnabled = false,
                            UserName = "Şevval Vural"
                        },
                        new
                        {
                            Id = new Guid("a77dcadd-68bb-42a4-b745-a4e84239046c"),
                            AccessFailedCount = 0,
                            Age = 25,
                            ConcurrencyStamp = "d8b173c8-4a67-4fec-a4e2-cf0051aae036",
                            Email = "rabia.canigur@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Rabia",
                            Gender = 1,
                            ImageUrl = "image32",
                            LastName = "Canıgür",
                            LockoutEnabled = false,
                            NormalizedEmail = "RABIACANIGUR@GMAIL.COM",
                            NormalizedUserName = "RABIACANIGUR@GMAIL.COM",
                            PhoneNumber = "+905439999932",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "d7053d69-2005-4038-bcd3-5837fc4d4f05",
                            TwoFactorEnabled = false,
                            UserName = "Rabia Canıgür"
                        },
                        new
                        {
                            Id = new Guid("e998015d-2878-4a92-9609-ed5dbe99b90f"),
                            AccessFailedCount = 0,
                            Age = 29,
                            ConcurrencyStamp = "e6485094-bd51-46f6-869d-fa91d190f6b7",
                            Email = "meltem.erkmen.kandil@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Meltem",
                            Gender = 1,
                            ImageUrl = "image33",
                            LastName = "Erkmen Kandil",
                            LockoutEnabled = false,
                            NormalizedEmail = "MELTEMERKMENKANDIL@GMAIL.COM",
                            NormalizedUserName = "MELTEMERKMENKANDIL@GMAIL.COM",
                            PhoneNumber = "+905439999933",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "d4477842-33ba-4788-901a-2609180d7f53",
                            TwoFactorEnabled = false,
                            UserName = "Meltem Erkmen Kandil"
                        },
                        new
                        {
                            Id = new Guid("e12dec13-61f5-4a44-8bc1-9a02eb7e0157"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "852df3c0-0345-4e67-b001-96260c1e1874",
                            Email = "ahmet.deniz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmet",
                            Gender = 2,
                            ImageUrl = "image34",
                            LastName = "Deniz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMETDENIZ@GMAIL.COM",
                            NormalizedUserName = "AHMETDENIZ@GMAIL.COM",
                            PhoneNumber = "+905439999934",
                            PhoneNumberConfirmed = true,
                            Score = 0,
                            SecurityStamp = "07af421b-a692-4534-ba11-635304e2ec8e",
                            TwoFactorEnabled = false,
                            UserName = "Ahmet Deniz"
                        },
                        new
                        {
                            Id = new Guid("588d197a-f7d8-433a-9ccb-a7e6e163af0d"),
                            AccessFailedCount = 0,
                            Age = 31,
                            ConcurrencyStamp = "e24fc613-3f0f-4523-8dde-82a5720639cb",
                            Email = "muhsin.cetinkaya@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Muhsin",
                            Gender = 2,
                            ImageUrl = "image35",
                            LastName = "Çetinkaya",
                            LockoutEnabled = false,
                            NormalizedEmail = "MUHSINCETINKAYA@GMAIL.COM",
                            NormalizedUserName = "MUHSINCETINKAYA@GMAIL.COM",
                            PhoneNumber = "+905439999935",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "aafcb90f-fcf2-439a-807f-a6391967d953",
                            TwoFactorEnabled = false,
                            UserName = "Muhsin Çetinkaya"
                        },
                        new
                        {
                            Id = new Guid("1117f3a4-f09c-419a-91b7-df35e577d686"),
                            AccessFailedCount = 0,
                            Age = 25,
                            ConcurrencyStamp = "98c65ed5-bbc0-466e-bb99-a8d546e1fb23",
                            Email = "sultan.ozmert@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Sultan",
                            Gender = 1,
                            ImageUrl = "image36",
                            LastName = "Özmert",
                            LockoutEnabled = false,
                            NormalizedEmail = "SULTANOZMERT@GMAIL.COM",
                            NormalizedUserName = "SULTANOZMERT@GMAIL.COM",
                            PhoneNumber = "+905430000036",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "e3087124-00b0-48dd-a409-17d706cb5aea",
                            TwoFactorEnabled = false,
                            UserName = "Sultan Özmert"
                        },
                        new
                        {
                            Id = new Guid("f2c8b5b0-0daa-49ff-8620-8faad7caa6bf"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "1cb0b351-ecc7-4a29-b964-ee9807c50969",
                            Email = "ahmet.alp.ozdemir@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Ahmet Alp",
                            Gender = 2,
                            ImageUrl = "image37",
                            LastName = "Özdemir",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMETALPOZDEMIR@GMAIL.COM",
                            NormalizedUserName = "AHMETALPOZDEMIR@GMAIL.COM",
                            PhoneNumber = "+905430000037",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "fe1451a8-6a8a-4dce-9a99-88db6ec02b03",
                            TwoFactorEnabled = false,
                            UserName = "Ahmet Alp Özdemir"
                        },
                        new
                        {
                            Id = new Guid("6255388e-bd0c-4834-8e30-0301506ea82c"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "c5737c6f-d1e8-4cac-bf4a-48132a88f6c8",
                            Email = "eylul.eda.cekmenoglu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Eylül Eda",
                            Gender = 1,
                            ImageUrl = "image38",
                            LastName = "Çekmenoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "EYLULEDACEKMENOGLU@GMAIL.COM",
                            NormalizedUserName = "EYLULEDACEKMENOGLU@GMAIL.COM",
                            PhoneNumber = "+905430000038",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "7f3abc0b-3b0e-47c2-b787-b5809a5a0d9d",
                            TwoFactorEnabled = false,
                            UserName = "Eylül Eda Çekmenoğlu"
                        },
                        new
                        {
                            Id = new Guid("bea47fb3-17d4-4be2-ae61-c4dba6f9c231"),
                            AccessFailedCount = 0,
                            Age = 26,
                            ConcurrencyStamp = "84c96e1a-6d74-4b87-91e4-e25b50ff684c",
                            Email = "zeynep.cemre.ordu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Zeynep Cemre",
                            Gender = 1,
                            ImageUrl = "image39",
                            LastName = "Ordu",
                            LockoutEnabled = false,
                            NormalizedEmail = "ZEYNEPCEMREORDU@GMAIL.COM",
                            NormalizedUserName = "ZEYNEPCEMREORDU@GMAIL.COM",
                            PhoneNumber = "+905430000039",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "94f2f7d6-7dcf-4a71-baa0-187d4e359331",
                            TwoFactorEnabled = false,
                            UserName = "Zeynep Cemre Ordu"
                        },
                        new
                        {
                            Id = new Guid("34252ab2-34ef-460b-bbd4-2ef2c6de2b08"),
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "ca42abfc-990d-4e6e-9c82-af36882edd09",
                            Email = "mihriban.akdemir@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mihriban",
                            Gender = 1,
                            ImageUrl = "image40",
                            LastName = "Akdemir",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIHRIBANAKDEMIR@GMAIL.COM",
                            NormalizedUserName = "MIHRIBANAKDEMIR@GMAIL.COM",
                            PhoneNumber = "+905430000040",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "33b73576-4d95-4baf-affd-1f175ea1fae2",
                            TwoFactorEnabled = false,
                            UserName = "Mihriban Akdemir"
                        },
                        new
                        {
                            Id = new Guid("dbfae5b3-9088-4978-b91c-aed5b4b2b447"),
                            AccessFailedCount = 0,
                            Age = 27,
                            ConcurrencyStamp = "dccf9b85-f8d7-4b0a-8939-2c7130d057d3",
                            Email = "buse.aydemir@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Buse",
                            Gender = 1,
                            ImageUrl = "image41",
                            LastName = "Aydemir",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUSEAYDEMIR@GMAIL.COM",
                            NormalizedUserName = "BUSEAYDEMIR@GMAIL.COM",
                            PhoneNumber = "+905430000041",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "51b340a2-9cfb-4495-8be8-c02a0dbad21d",
                            TwoFactorEnabled = false,
                            UserName = "Buse Aydemir"
                        },
                        new
                        {
                            Id = new Guid("83daecf7-ac0f-4370-b87f-7cd653a8cd9b"),
                            AccessFailedCount = 0,
                            Age = 23,
                            ConcurrencyStamp = "a871841a-7cbe-4150-befd-533559238378",
                            Email = "sevval.nilsu.tarhan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Şevval Nilsu",
                            Gender = 1,
                            ImageUrl = "image42",
                            LastName = "Tarhan",
                            LockoutEnabled = false,
                            NormalizedEmail = "SEVVALNILSUTARHAN@GMAIL.COM",
                            NormalizedUserName = "SEVVALNILSUTARHAN@GMAIL.COM",
                            PhoneNumber = "+905430000042",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "2e914bf2-4e9c-42e7-a3db-8a154001fbd2",
                            TwoFactorEnabled = false,
                            UserName = "Şevval Nilsu Tarhan"
                        },
                        new
                        {
                            Id = new Guid("63d25a80-30cb-4e23-850b-24ba5de06467"),
                            AccessFailedCount = 0,
                            Age = 29,
                            ConcurrencyStamp = "381be9ca-39e0-480e-a521-d02b8dc84041",
                            Email = "melisa.kizilhisar@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Melisa",
                            Gender = 1,
                            ImageUrl = "image43",
                            LastName = "Kızılhisar",
                            LockoutEnabled = false,
                            NormalizedEmail = "MELISAKIZILHISAR@GMAIL.COM",
                            NormalizedUserName = "MELISAKIZILHISAR@GMAIL.COM",
                            PhoneNumber = "+905430000043",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "0efbd425-7f45-4ef9-b290-5b45b38169fa",
                            TwoFactorEnabled = false,
                            UserName = "Melisa Kızılhisar"
                        },
                        new
                        {
                            Id = new Guid("f2578473-6c8a-4290-bf80-6785b057b5ee"),
                            AccessFailedCount = 0,
                            Age = 31,
                            ConcurrencyStamp = "059e63be-76c4-4233-9bb4-832af4a9b10c",
                            Email = "betul.emel.butuner@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Betül Emel",
                            Gender = 1,
                            ImageUrl = "image44",
                            LastName = "Bütüner",
                            LockoutEnabled = false,
                            NormalizedEmail = "BETULEMELBUTUNER@GMAIL.COM",
                            NormalizedUserName = "BETULEMELBUTUNER@GMAIL.COM",
                            PhoneNumber = "+905430000044",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "a23bdd2a-0289-478c-bd47-bdcad3f13ab7",
                            TwoFactorEnabled = false,
                            UserName = "Betül Emel Bütüner"
                        },
                        new
                        {
                            Id = new Guid("6a5fa385-1e66-4faf-a2b2-4afd5b455155"),
                            AccessFailedCount = 0,
                            Age = 32,
                            ConcurrencyStamp = "6cab9c7e-fa21-4429-9846-470c8d6b8e8f",
                            Email = "baris.keles@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Barış",
                            Gender = 2,
                            ImageUrl = "image45",
                            LastName = "Keleş",
                            LockoutEnabled = false,
                            NormalizedEmail = "BARISKELES@GMAIL.COM",
                            NormalizedUserName = "BARISKELES@GMAIL.COM",
                            PhoneNumber = "+905430000045",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "a56469d6-a45c-49ae-a928-145b95239773",
                            TwoFactorEnabled = false,
                            UserName = "Barış Keleş"
                        },
                        new
                        {
                            Id = new Guid("a2f60320-8e33-4542-a0cc-d7b927913727"),
                            AccessFailedCount = 0,
                            Age = 21,
                            ConcurrencyStamp = "c0e4e0c6-e164-4f5e-9687-e56f809dbd50",
                            Email = "lara.dinc@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Lara",
                            Gender = 1,
                            ImageUrl = "image46",
                            LastName = "Dinç",
                            LockoutEnabled = false,
                            NormalizedEmail = "LARADINC@GMAIL.COM",
                            NormalizedUserName = "LARADINC@GMAIL.COM",
                            PhoneNumber = "+905430000046",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "033583f4-b058-481e-8a12-72d2390b833c",
                            TwoFactorEnabled = false,
                            UserName = "Lara Dinç"
                        },
                        new
                        {
                            Id = new Guid("ed63def8-9eeb-4ff2-b67c-2e7b8983ad37"),
                            AccessFailedCount = 0,
                            Age = 28,
                            ConcurrencyStamp = "9002dd95-dac6-40cd-b062-dd4bf1f2d1b1",
                            Email = "busra.selimoglu@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Büşra",
                            Gender = 1,
                            ImageUrl = "image47",
                            LastName = "Selimoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "BUSRASELIMOGLU@GMAIL.COM",
                            NormalizedUserName = "BUSRASELIMOGLU@GMAIL.COM",
                            PhoneNumber = "+905430000047",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "ffae3091-0843-4372-800d-3ac0538085d7",
                            TwoFactorEnabled = false,
                            UserName = "Büşra Selimoğlu"
                        },
                        new
                        {
                            Id = new Guid("19241570-1d71-4824-9d55-24c79ea1227c"),
                            AccessFailedCount = 0,
                            Age = 24,
                            ConcurrencyStamp = "7b27de7f-4b82-4df7-84dc-050b1b891d2c",
                            Email = "doga.mert@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Doğa",
                            Gender = 2,
                            ImageUrl = "image48",
                            LastName = "Mert",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOGAMERT@GMAIL.COM",
                            NormalizedUserName = "DOGAMERT@GMAIL.COM",
                            PhoneNumber = "+905430000048",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "19887033-c922-4d15-8649-b42382bd4804",
                            TwoFactorEnabled = false,
                            UserName = "Doğa Mert"
                        },
                        new
                        {
                            Id = new Guid("0de5199d-6f0a-46a3-a574-6d9dd5dd7de7"),
                            AccessFailedCount = 0,
                            Age = 22,
                            ConcurrencyStamp = "2a219afe-baf8-440e-8f91-b89af9381c92",
                            Email = "yaren.turgut@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Yaren",
                            Gender = 1,
                            ImageUrl = "image49",
                            LastName = "Turgut",
                            LockoutEnabled = false,
                            NormalizedEmail = "YARENTURGUT@GMAIL.COM",
                            NormalizedUserName = "YARENTURGUT@GMAIL.COM",
                            PhoneNumber = "+905430000049",
                            PhoneNumberConfirmed = false,
                            Score = 0,
                            SecurityStamp = "9720abd0-e881-43f6-a264-9960c16698b1",
                            TwoFactorEnabled = false,
                            UserName = "Yaren Turgut"
                        });
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("cb94223b-ccb8-4f2f-93d7-0df96a7f065c"),
                            RoleId = new Guid("16ea936c-7a28-4c30-86a2-9a9704b6115e")
                        },
                        new
                        {
                            UserId = new Guid("3aa42229-1c0f-4630-8c1a-db879ecd0427"),
                            RoleId = new Guid("edf6c246-41d8-475f-8d92-41dddac3aefb")
                        });
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0299a520-25ca-49ec-9492-035ccf2ed5b8"),
                            BadgeIcon = "https://w7.pngwing.com/pngs/423/1004/png-transparent-medal-gold-winner-badge-achievement-reward-army-champion-awards-icon.png",
                            BadgeName = "Dilek Perisi",
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 13, 25, 54, 221, DateTimeKind.Local).AddTicks(9518),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("6296d6f2-052e-40fb-bf0b-72eb2ac34a6d"),
                            BadgeIcon = "https://static.vecteezy.com/system/resources/previews/014/606/031/original/golden-yellow-trophy-icon-for-the-winner-of-a-sports-event-png.png",
                            BadgeName = "Dilek Yıldızı",
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 13, 25, 54, 221, DateTimeKind.Local).AddTicks(9580),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("820b74d4-c6f7-4823-a45e-6dbd41311212"),
                            BadgeIcon = "https://e7.pngegg.com/pngimages/1002/183/png-clipart-smiley-smiley-miscellaneous-smiley.png",
                            BadgeName = "Gülen Yüz",
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 13, 25, 54, 221, DateTimeKind.Local).AddTicks(9588),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1328a6c8-9ebd-4b22-978a-453f0c31bbdf"),
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 10, 25, 54, 222, DateTimeKind.Utc).AddTicks(1061),
                            EventName = "Diğer Gönüllü Faaliyetleri",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("1e7bc8e4-59a8-4f63-af21-c7697a727f64"),
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 10, 25, 54, 222, DateTimeKind.Utc).AddTicks(1067),
                            EventName = "Dilek Alma Etkinliği",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("3c5b8e39-a8f8-4671-a573-2e1e5e8a6f85"),
                            CreatedBy = "Undefined",
                            CreatedDate = new DateTime(2024, 12, 5, 10, 25, 54, 222, DateTimeKind.Utc).AddTicks(1070),
                            EventName = "Dilek Gerçekleştirme Etkinliği",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.UserEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("EventId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppRoleClaim", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserClaim", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserLogin", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserRole", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DilekYildizimSensin.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUserToken", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.UserBadge", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppUser", "AppUser")
                        .WithMany("UserBadges")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DilekYildizimSensin.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.UserEvent", b =>
                {
                    b.HasOne("DilekYildizimSensin.Models.AppUser", "AppUser")
                        .WithMany("UserEvents")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DilekYildizimSensin.Models.Event", "Event")
                        .WithMany("UserEvents")
                        .HasForeignKey("EventId");

                    b.Navigation("AppUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.AppUser", b =>
                {
                    b.Navigation("UserBadges");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("DilekYildizimSensin.Models.Event", b =>
                {
                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
